hon2.7/dist-packages/django/db/backends/base/base.py", line 564, in temporary_connection
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     cursor = self.cursor()Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 231, in cursor
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     cursor = self.make_debug_cursor(self._cursor())
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     self.ensure_connection()
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     self.connect()
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     self.connect()
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     self.connection = self.get_new_connection(conn_params)
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 263, in get_new_connection
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     conn = Database.connect(**conn_params)
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     return Connection(*args, **kwargs)
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns:     super(Connection, self).__init__(*args, **kwargs2)
Notice: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]/returns: django.db.utils.OperationalError: (1049, "Unknown database 'mydb'")
Error: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]: Failed to call refresh: '/usr/bin/python manage.py createdb --noinput' returned 1 instead of one of [0]
Error: /Stage[main]/Myblog::Create_project/Exec[init-mezzanine-db]: '/usr/bin/python manage.py createdb --noinput' returned 1 instead of one of [0]
